# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('vinculated_institutions', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('C', 'Completo'), ('EP', 'En proceso'), ('S', 'Suspendido')], default='EP', max_length=1)),
                ('areas', models.ManyToManyField(to='core.Area')),
            ],
        ),
    ]
