# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('C', 'Completo'), ('EP', 'En proceso'), ('S', 'Suspendido')], default='EP', max_length=2),
        ),
    ]
