# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ['-created_at']},
        ),
    ]
