# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_updatefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
