# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20181025_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=projects.models.project_img_path),
        ),
    ]
