# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181101_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='projectupdatecomment',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
