# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181013_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='research_group',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.ResearchGroup'),
        ),
    ]
