# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_personal_research_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='research_group',
            new_name='research_groups',
        ),
    ]
