# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 02:11
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181018_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_img_path),
        ),
    ]
